### ISSUE TITLE
Darts DNN predict

### ISSUE THREAD

**Issue by YangpingLi** [Xinglab/DARTS#17]
Hi,

I got my "A5SS.darts_bht.flat.txt" by:

**Darts_BHT rmats_count --b1 con1.sorted.bam --b2 con2.sorted.bam --gtf hg38.genes.gtf --od DARTS_out -t paired --nthread 24 --readLength 151
Darts_BHT bayes_infer --rmats-count DARTS_out/JC.raw.input.A5SS.txt --od ./DARTS_out --annot DARTS_out/fromGTF.A5SS.txt -t A5SS -c 0.05 --nthread 8**

and 
kallisto gene exoression file by:
**kallisto quant -i hg19 -o con1 con1_1.fq con1_2.fq**

but when I try to run:
**Darts_DNN predict -i ../DARTS_out/A5SS.darts_bht.flat.txt -e kallisto/con1 kallisto/con2 -o pred.txt -t A5SS**

I got this error massage:

Traceback (most recent call last):
  File "/projects/compbio/users/byao5/anaconda3/envs/darts/bin/Darts_DNN", line 4, in <module>
    __import__('pkg_resources').run_script('Darts-DNN==0.1.0', 'Darts_DNN')
  File "/projects/compbio/users/byao5/anaconda3/envs/darts/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/projects/compbio/users/byao5/anaconda3/envs/darts/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/projects/compbio/users/byao5/anaconda3/envs/darts/lib/python2.7/site-packages/Darts_DNN-0.1.0-py2.7.egg/EGG-INFO/scripts/Darts_DNN", line 192, in <module>

  File "/projects/compbio/users/byao5/anaconda3/envs/darts/lib/python2.7/site-packages/Darts_DNN-0.1.0-py2.7.egg/EGG-INFO/scripts/Darts_DNN", line 44, in main

  File "/projects/compbio/users/byao5/anaconda3/envs/darts/lib/python2.7/site-packages/Darts_DNN-0.1.0-py2.7.egg/Darts_DNN/Darts_pred.py", line 107, in parser
  File "/projects/compbio/users/byao5/anaconda3/envs/darts/lib/python2.7/site-packages/Darts_DNN-0.1.0-py2.7.egg/Darts_DNN/Darts_pred.py", line 51, in eval_continuous_label_auc
  File "/projects/compbio/users/byao5/anaconda3/envs/darts/lib/python2.7/site-packages/sklearn/metrics/ranking.py", line 352, in roc_auc_score
    y_true = label_binarize(y_true, labels)[:, 0]
  File "/projects/compbio/users/byao5/anaconda3/envs/darts/lib/python2.7/site-packages/sklearn/preprocessing/label.py", line 581, in label_binarize
    y = check_array(y, accept_sparse='csr', ensure_2d=False, dtype=None)
  File "/projects/compbio/users/byao5/anaconda3/envs/darts/lib/python2.7/site-packages/sklearn/utils/validation.py", line 582, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.

Since I can run the test file from "A5SS.thymus_adipose.tgz" quiet well. I compared those two flat file and found:
The format is different:
darts_bht.flat.txt from "A5SS.thymus_adipose.tgz":
ID      I1      S1      I2      S2      inc_len skp_len mu.mle  delta.mle       post_pr

A5SS.darts_bht.flat.txt of me:
ID      I1      S1      I2      S2      inc_len skp_len psi1    psi2    delta.mle       post_pr

Is this the reason that I cannot run "Darts DNN predict"?
Do you have any suggestion on that?

Thanks for advance!

Yangping

**Comment by YangpingLi** [comment]
I've used hg38 to generate the bam file before. Now I changed it to hg19 and problem solved!!!
Thanks!
