### ISSUE TITLE
Does Darts works to the outlier(unpaired) analysis?

### ISSUE THREAD

**Issue by sitongc** [Xinglab/DARTS#22]
Hi,
I try to run Darts in my 1 v 3 group, but it always give me an error when I run bayers_infer: 

rpy2.rinterface.rruntimeerror: error in { : task 1 failed - "non-finite value supplied by optim"

Here is my code:

Darts_BHT bayes_infer --rmats-count JC.raw.input.A5SS.txt --od ./ --annot fromGTF.A5SS.txt -t A5SS -c 0.05 --nthread 8

Do you have any suggestions?

Best,
Sitong

**Comment by zj-zhang** [comment]
Hi @sitongc It looks like your run failed because Darts can't estimate a valid group variance when one of your groups has only 1 sample. You may want to try adding the "--replicate-model pooled" to merge the replicates with 3 samples, and run a pooled model.
`Darts_BHT bayes_infer --rmats-count JC.raw.input.A5SS.txt --od ./ --annot fromGTF.A5SS.txt -t A5SS -c 0.05 --nthread 8
--replicate-model pooled`

**Comment by sitongc** [comment]
@zj-zhang Thank you! That solved my problem.

**Comment by sitongc** [comment]
Hi @zj-zhang, thank you for your reply. 

I try to run my analysis by your code, but it is still give me the same error. 

Darts_BHT bayes_infer --rmats-count JC.raw.input.A5SS.txt --od ./ --annot fromGTF.A5SS.txt -t A5SS -c 0.05 --nthread 8 --replicate-model pooled
2022-08-17 18:09:17,143 - Darts_BHT.bayes_infer - INFO -
 Coverting rMATS count to Darts format
2022-08-17 18:09:17,205 - Darts_BHT.bayes_infer - INFO -
 input count=./A5SS.input.txt
2022-08-17 18:09:17,206 - Darts_BHT.bayes_infer - INFO -
 output dir=./
2022-08-17 18:09:17,216 - Darts_BHT.bayes_infer - INFO -
 detected input file has no replicates; your "replicate_model" or "estim_gVar" options will be ignored
2022-08-17 18:09:17,217 - Darts_BHT.bayes_infer - INFO -
 using no-replicate model
no. of threads using = 8
  |======================================================================| 100%/home/ec2-user/miniconda3/envs/darts/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Error in { : task 1 failed - "non-finite value supplied by optim"

  warnings.warn(x, RRuntimeWarning)
Traceback (most recent call last):
  File "/home/ec2-user/miniconda3/envs/darts/bin/Darts_BHT", line 152, in <module>
    main()
  File "/home/ec2-user/miniconda3/envs/darts/bin/Darts_BHT", line 48, in main
    BHT_wrapper.parser( args )
  File "/home/ec2-user/miniconda3/envs/darts/lib/python2.7/site-packages/Darts_BHT-0.1.0-py2.7.egg/Darts_BHT/BHT_wrapper.py", line 231, in parser
  File "/home/ec2-user/miniconda3/envs/darts/lib/python2.7/site-packages/Darts_BHT-0.1.0-py2.7.egg/Darts_BHT/BHT_wrapper.py", line 54, in run_darts_BHT_norep
  File "/home/ec2-user/miniconda3/envs/darts/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/home/ec2-user/miniconda3/envs/darts/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in { : task 1 failed - "non-finite value supplied by optim"

**Comment by zj-zhang** [comment]
OK this could be tricky as the error msg is not very helpful. Could you let me know if you were able to run the test dataset (link below) without a problem?
https://github.com/Xinglab/DARTS/tree/master/Darts_BHT/test_data
