### ISSUE TITLE
Darts_DNN predict error

### ISSUE THREAD

**Issue by hubentu** [Xinglab/DARTS#4]
Hi,
I followed the instruction to install the darts_dnn and darts_bht using conda, but I got an error from the testing example. Any help? Thanks!

$Darts_DNN predict -i darts_bht.flat.txt -e RBP_tpm.txt -o pred.txt -t A5SS

```
Darts_DNN predict -i darts_bht.flat.txt -e RBP_tpm.txt -o pred.txt -t A5SS
Using TensorFlow backend.
2019-03-26 10:47:26,871 - Darts_DNN.predict - INFO -
 empirical_data=darts_bht.flat.txt
2019-03-26 10:47:26,872 - Darts_DNN.predict - INFO -
 model=/home/bios1/.darts/DNN/v0.1.0/trainedParam/A5SS-trainedParam-EncodeRoadmap.h5
Traceback (most recent call last):
  File "/home/bios1/anaconda3/envs/darts/bin/Darts_DNN", line 4, in <module>
    __import__('pkg_resources').run_script('Darts-DNN==0.1.0', 'Darts_DNN')
  File "/home/bios1/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/bios1/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1524, in run_script
    exec(script_code, namespace, namespace)
  File "/home/bios1/anaconda3/envs/darts/lib/python2.7/site-packages/Darts_DNN-0.1.0-py2.7.egg/EGG-INFO/scripts/Darts_DNN", line 192, in <module>
    
  File "/home/bios1/anaconda3/envs/darts/lib/python2.7/site-packages/Darts_DNN-0.1.0-py2.7.egg/EGG-INFO/scripts/Darts_DNN", line 44, in main
    
  File "/home/bios1/anaconda3/envs/darts/lib/python2.7/site-packages/Darts_DNN-0.1.0-py2.7.egg/Darts_DNN/Darts_pred.py", line 69, in parser
  File "/home/bios1/anaconda3/envs/darts/lib/python2.7/site-packages/Darts_DNN-0.1.0-py2.7.egg/Darts_DNN/sklearn_nn.py", line 51, in __init__
  File "/home/bios1/anaconda3/envs/darts/lib/python2.7/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/bios1/anaconda3/envs/darts/lib/python2.7/site-packages/keras/layers/core.py", line 883, in call
    output = self.activation(output)
  File "/home/bios1/anaconda3/envs/darts/lib/python2.7/site-packages/keras/activations.py", line 31, in softmax
    return K.softmax(x)
  File "/home/bios1/anaconda3/envs/darts/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 3231, in softmax
    return tf.nn.softmax(x, axis=axis)
TypeError: softmax() got an unexpected keyword argument 'axis'
```

**Comment by zj-zhang** [comment]
@hubentu This is an issue of version incompatibility between keras and tensorflow, encountered by many users beginning last year. 
Referring to 
https://github.com/keras-team/keras/issues/9621
I am using keras 2.2.4 and tensorflow 1.12.0, which works fine. You can also try switching to Theano backend for keras.

**Comment by hubentu** [comment]
Hi @zj-zhang ,

I also installed the same version of keras and tensorflow. They didn't work for me. Thanks!

$conda list
```
# Name                    Version                   Build  Channel
keras                     2.2.4                         0  
keras-applications        1.0.7                      py_0  
keras-base                2.2.4                    py27_0  
keras-preprocessing       1.0.9                      py_0  
tensorflow                1.12.0          mkl_py27hc55d17a_0  
tensorflow-base           1.12.0          mkl_py27h3c3e929_0  
```

**Comment by zj-zhang** [comment]
Hi @hubentu 
Could you please confirm you still have the same issue in "softmax" layer by running the minimal Python code snippet below?
```{python}
from keras.models import Sequential
model = Sequential()
from keras.layers import Dense
model.add(Dense(units=64, activation='relu', input_dim=100))
model.add(Dense(units=10, activation='softmax'))
model.compile(loss='categorical_crossentropy',
              optimizer='sgd',
              metrics=['accuracy'])
model.summary()

import Darts_DNN.config; print("Darts_DNN==%s"%Darts_DNN.config.CURRENT_VERSION)
```

**Comment by hubentu** [comment]
Yes. I got the same error.
```
TypeError: softmax() got an unexpected keyword argument 'axis'
```

To change the `activation='softmax'` to `activation=tf.nn.softmax` works for me.

**Comment by zj-zhang** [comment]
Looks like a Keras/Tensorflow issue. Please follow the response in this link to adjust the versions/configs:
https://github.com/keras-team/keras/issues/9621
Will add more version requirements in the next release. Closing for now.
